@model AtomicG.Core.Models.TemplateModel
@using AtomicG.Helper
<template>
  <div>
    <p>This site was generated by <a href="https://www.atomicg.dev" target="_blank">AtomicG</a></p>
    <hr />
    <ul>
@foreach (var entity in Model.Entities)
{
        <li><router-link to="/@entity.Name.Pluralize()">@entity.Name.Pluralize().FirstLetterToUpper()</router-link></li>
}
    </ul>
  </div>
</template>

<script>
export default {
  name: 'Home'
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>